---
title: "Hw_5'"
author: "PranithaMahesh"
date: "27/02/2020"
output: html_document
---

```{r}
install.packages("tidyverse")
library(tidyverse)
```
```{r}
head(diamonds)
```


```{r}
#1.Plot a bar chart by cut for the data set diamonds.
ggplot(diamonds, aes(x = cut, fill=cut)) + geom_bar()
```
```{r}
#2.Plot a bar chart (proprtions) by cut for the data set diamonds, and give them a gray color.
ggplot(data = diamonds, aes(x = cut,y=..prop..,group = 1, fill=cut)) +
  geom_bar(colour = "Light Grey")
```
```{r}
#3.Plot a stacked bar chart for cut by clarity.
ggplot(data = diamonds, aes(x = cut , fill = clarity)) +
  geom_bar()
```

```{r}
#4.For each cut, set the bars of the variable clarity side-by-side.
ggplot(data = diamonds, aes(x = cut , fill = clarity)) +
  geom_bar(position = "dodge")
```

```{r}
#5. Repeat #4 above but change y- axis to show proportions.
ggplot(data = diamonds, aes(x = cut ,fill = clarity)) +
  geom_bar(position = "dodge", mapping = aes(y = ..prop..,group = clarity))
```

```{r}
#6.Facet wrap by clarity
ggplot(data = diamonds, aes(x = cut ,y = ..prop..,fill = clarity)) +
  geom_bar(position = "dodge", mapping = aes(y = ..prop..,group = clarity)) +
  facet_wrap( ~clarity)
```

